name: Caching and Artifacts with CI
on: [workflow_dispatch]

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache-dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'
      - name: Install dependencies
        run: npm ci
      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios')
            const res = await axios('https://icanhazdadjoke.com/', {headers: {Accept: 'text/plain'}})
            console.log(res.data)
