name: Decrypting Secret
on: [push]

jobs:
  decrypt-file:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE}}
        run: |
          mkdir $HOME/secrets
          gpg --batch --yes \
            --pinentry-mode loopback \
            --passphrase "$PASSPHRASE" \
            --decrypt \
            --output "$HOME/secrets/secret.json" \
            secret.json.gpg
      - name: View Encrypted File Content
        run: cat "$HOME/secrets/secret.json"
