#-------------------------------------------------------------
# https://hub.docker.com/_/node/
#-------------------------------------------------------------
name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:25-alpine3.22
    env:
      API_URL: some-url.com

    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log Env
        run: echo $API_URL
