# Same information can be used as environment variables and also as context.
# Difference:
#   Environment variable $GITHUB_REF will run on the runner machine
#   '${{ github.ref }}' will be evaluated by github actions before workflow is sent to the runner machine
#   ... it is sent to the runner machine already evaluated

name: Environment Variables
on: [push]

env:
  WF_LEVEL_ENV: Available to all jobs
jobs:
  env-vars-and-context:
    runs-on: ubuntu-latest
    # processed before reaches runner machine, so u must use it this way
    if: github.ref == 'refs/heads/main'
    env:
      # available only to 'env-vars-and context' job (local)
      JOB_LEVEL_ENV: Available to all steps in env-vars-and context job
    steps:
      - name: Log ENV VAR
        run: echo $GITHUB_REF
      - name: Log Context
        run: echo '${{ github.ref }}'
      - name: Set Environment Variable
        run: |
          echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"
          echo "JOB_LEVEL_ENV=$RANDOM" >> "$GITHUB_ENV"
      - name: Log Custom ENV Vars
        env:
          STEP_LEVEL_ENV: Available only to this step
          WF_LEVEL_ENV: Overriden in step
        run: |
          echo '${{ env.STEP_LEVEL_ENV }}' # evaluated by github actions, not runner machine, ok to use in if-statemtn
          echo $STEP_LEVEL_ENV             # evaluated on runner machine, cannot use in if-statement
          echo $WF_LEVEL_ENV
          echo $JOB_LEVEL_ENV
          echo $NEW_ENV_VAR
