# the workflow is triggered to run based on an external action.
# Must be pushed to our default main branch.

# note: env is expected in the postman client_payload, must match

name: External Events
on:
  repository_dispatch:
    types: [build]
jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.env }} # evaluate expression with this syntax
