---
#------------------------------------------------------------------
# evaluating expression inside single quotes: $ + 2 curly brackets
#------------------------------------------------------------------
# Contexts
# toJson(github) gives information about repo
# toJson(job) info about the job
#------------------------------------------------------------------
name: Expressions & Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "If Statement by @${{ github.actor }}, event: ${{github.event_name}}"

jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(job) }}'
          echo '${{ toJson(runner) }}'
