name: Initial Orchesterator to Nested Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Keyhan"
        required: false
jobs:
  calling-a-reusable-wf-in-the-same-repo:
    uses: ./.github/workflows/reusable-wf.yaml
    secrets: inherit
  using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf-in-the-same-repo
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}
