name: Origin of Nested Workflows

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Keyhan"
        required: false

jobs:
  calling-internal-wf:
    uses: ./.github/workflows/reusable-wf.yaml
    secrets: inherit

  calling-external-wf:
    needs: calling-internal-wf
    uses: Alaa-Organization/workflows/.github/workflows/reusable.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets: inherit

  using-reusable-wf-output:
    needs: calling-internal-wf
    runs-on: ubuntu-latest
    steps:
      - run: echo "Date from internal workflow ${{ needs.calling-internal-wf.outputs.date }}"
