name: Job Level Timeout
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Step 1
        run: sleep 90
      - name: Step 2
        id: step-2
        continue-on-error: true # entire job doesn't fail (if: success() executes)
        run: exit 1
      - name: Runs on Step 2 Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has failed'
      - name: Runs on Failure
        if: failure()
        run: echo 'Failure'
      - name: Runs on Success
        # this is not needed (default behavior)
        if: success()
        run: echo 'Runs on Success'
      - name: Always Runs
        if: always()
        run: echo 'Always Runs'
      - name: Runs When Cancelled
        if: cancelled()
        run: echo 'Runs on Cancelled'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'
