name: Internal Reusable Workflow
on:
  workflow_call:
    outputs:
      date:
        description: "Date Value"
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  nested-workflow-call:
    uses: Alaa-Organization/workflows/.github/workflows/reusable.yaml@main
    with:
      name: "kman" # my local inputs
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

  generate-output:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date-step.outputs.date }}
    steps:
      - run: echo "date=$(date)" >> $GITHUB_OUTPUT
        id: date-step
