# this workflow calls 'Repository Events' and on Repository Events completion, this workflow will run

name: Wf Run After Repository Event
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered because 'Repository Events' was completed"
